/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JoeyNutria (https://sketchfab.com/JoeyNutria)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pink-retro-computer-e7bd70ee0e9548d9bef951c7b1ca9a2f
Title: Pink Retro Computer
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pink_retro_computer/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -1.059]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.Computer}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.Computer}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.Computer}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pink_retro_computer/scene.gltf')

